shop:
  eureka:
    hostname: localhost
eureka:
  client:
    service-url:
      defaultZone: http://${shop.eureka.hostname}:8761/eureka/

---
spring.profiles: docker

shop:
  eureka:
    hostname: eureka