spring:
  datasource:
    url: jdbc:mysql://localhost:3306/goldenrelations
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa.hibernate.ddl-auto: update

security:
  oauth2:
    client:
      clientId: 192409514505352
      clientSecret: d7a4573bad0f4dac73ec7cd2982037bb
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.security: DEBUG

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port